### PR TITLE
Python implementation

### PR DESCRIPTION
**Pull request by Finnventor**
Here's a python implementation of the port4me algorithm. (#17 )

Roadmap:

- [x] Find out why this is giving different output for user='alice', tool='jupyter-notebook', even though it gives the correct output for alice, alice and rstudio, and bob
- [x] Add support for retrieving multiple ports (should there be two separate functions for this? or one function that sometimes returns an int, and sometimes returns a list? or a python generator object that yields arbitrarily many ports?)
- [x] Add support for prepend and exclude

### CODE REVIEW

**Comment by HenrikBengtsson** [comment]
Excellent and, wow, that was fast. I'll try to have a look later today.  One request though, could you make the `tool` argument the first argument?  This is to align it with the current behavior in Bash (and R), where:

```sh
$ jupyter notebook --port "$(port4me jupyter-notebook)"
```

is short for

```sh
$ jupyter notebook --port "$(port4me --tool=jupyter-notebook)"
```

which should make the most common use cases a bit less verbose. This is in new behavior in **port4me** 0.5.1, which I released literally within the last 30 minutes.

**Comment by HenrikBengtsson** [comment]
> Find out why this is giving different output for user='alice', tool='jupyter-notebook', even though it gives the correct output for alice, alice and rstudio, and bob

A wild guess, but it could be an overflow issue in the string hash implementation that kicks in when the combined string gets long enough.

Try with

```
portme --user=abcde
portme --user=abcdef
portme --user=abcdefg
portme --user=abcdefgh
...
```

and compare with what you get in Python. If my hypothesis is correct, then you'll eventually see a difference between Bash and Python.

**Comment by Finnventor** [comment]
I thought so too, but the algorithms look identical, and I wasn't able to get a different result even with a long string with special characters.
It turns out that for user=alice tool=jupyter-notebook the python version and the bash version both give 29525 as the first port they check, but the readme says it should be 47467, maybe that came from a different version of the implementation?
https://github.com/HenrikBengtsson/port4me/blob/7f53e777d6cfa9ac1144b51c1230d1bcfe144123/README.md?plain=1#L145-L146

**Comment by HenrikBengtsson** [comment]
> t turns out that for user=alice tool=jupyter-notebook the python version and the bash version both give 29525 as the first port they check, but the readme says it should be 47467, maybe that came from a different version of the implementation?

Oh, you're right, it should give port 29525, e.g.

```sh
$ bash/port4me port4me --user=alice --tool=jupyter-notebook --list=5
29525
51728
12991
56881
6244
```

I've updated the README and added this to the Bash and R unit tests (although not really needed), cf. commit 7f7ac2af3.

**Pull request merged**
